import {
  parse,
  TYPE,
  type MessageFormatElement,
} from "@formatjs/icu-messageformat-parser";

export interface KeyArgType {
  /** Name of the argument as referenced in the message string. */
  name: string;
  /** TS type expression: `string`, `number`, `Date | number`, `(chunks: ReactNode) => ReactNode`. */
  tsType: string;
}

export interface KeySchema {
  /** Dot-notation key, e.g. "checkout.confirm". */
  key: string;
  /** Raw message string from the base locale, used as the `__raw` literal. */
  raw: string;
  /** Inferred argument types for the message, deduped by name. */
  args: KeyArgType[];
}

/**
 * Walk a flat key → raw-message map and produce typed key schemas.
 * Bad/unparseable strings still emit an entry with no args (so missing
 * keys still type-check as usable; we just lose argument inference).
 */
export function inferSchemas(flat: Record<string, string | null>): KeySchema[] {
  const out: KeySchema[] = [];
  for (const key of Object.keys(flat).sort()) {
    const raw = flat[key];
    if (typeof raw !== "string") continue;
    out.push({ key, raw, args: inferArgs(raw) });
  }
  return out;
}

function inferArgs(message: string): KeyArgType[] {
  let ast: MessageFormatElement[];
  try {
    ast = parse(message, { requiresOtherClause: false });
  } catch {
    return [];
  }
  const args = new Map<string, string>();
  collect(ast, args);
  return [...args.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, tsType]) => ({ name, tsType }));
}

function collect(
  nodes: MessageFormatElement[],
  args: Map<string, string>,
): void {
  for (const node of nodes) {
    switch (node.type) {
      case TYPE.argument:
        merge(args, node.value, "string | number");
        break;
      case TYPE.number:
        merge(args, node.value, "number");
        break;
      case TYPE.date:
      case TYPE.time:
        merge(args, node.value, "Date | number");
        break;
      case TYPE.plural:
      case TYPE.select: {
        merge(
          args,
          node.value,
          node.type === TYPE.plural ? "number" : "string",
        );
        for (const branch of Object.values(node.options)) {
          collect(branch.value, args);
        }
        break;
      }
      case TYPE.tag:
        merge(args, node.value, "(chunks: ReactNode) => ReactNode");
        collect(node.children, args);
        break;
    }
  }
}

function merge(args: Map<string, string>, name: string, ts: string): void {
  const existing = args.get(name);
  // Prefer the most specific type already seen.
  if (existing && rank(existing) >= rank(ts)) return;
  args.set(name, ts);
}

function rank(ts: string): number {
  // Higher = more specific. (chunks: ReactNode) wins over number wins over Date wins over string|number.
  if (ts.startsWith("(chunks")) return 4;
  if (ts === "number") return 3;
  if (ts === "Date | number") return 2;
  if (ts === "string") return 1;
  return 0;
}

export function renderMessagesDts(schemas: KeySchema[]): string {
  const needsReactNode = schemas.some((s) =>
    s.args.some((a) => a.tsType.includes("ReactNode")),
  );
  const header = [
    "// Auto-generated by `api18n pull` — do not edit by hand.",
    "import 'api18n';",
    ...(needsReactNode ? ["import type { ReactNode } from 'react';"] : []),
    "",
    "declare module 'api18n' {",
    "  interface Messages {",
  ];
  const body = schemas.map((s) => `    ${quoteKey(s.key)}: ${renderEntry(s)};`);
  const footer = ["  }", "}", ""];
  return [...header, ...body, ...footer].join("\n");
}

function renderEntry(schema: KeySchema): string {
  const parts = [`__raw: ${quoteString(schema.raw)}`];
  for (const arg of schema.args) {
    parts.push(`${quoteKey(arg.name)}: ${arg.tsType}`);
  }
  return `{ ${parts.join("; ")} }`;
}

const SAFE_IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function quoteKey(key: string): string {
  return SAFE_IDENT.test(key) ? key : quoteString(key);
}

function quoteString(s: string): string {
  return `'${s.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n").replace(/\r/g, "\\r")}'`;
}
